package io.github.ptitjes.konvo.frontend.compose.toolkit.theme

import androidx.compose.material3.*
import androidx.compose.ui.graphics.*

private val primaryLight = Color(0xFF5D26C2)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFF7645DB)
private val onPrimaryContainerLight = Color(0xFFEBDFFF)
private val secondaryLight = Color(0xFF675493)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFCCB6FD)
private val onSecondaryContainerLight = Color(0xFF574482)
private val tertiaryLight = Color(0xFF96004F)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFC20068)
private val onTertiaryContainerLight = Color(0xFFFFD5E0)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF93000A)
private val backgroundLight = Color(0xFFFEF7FF)
private val onBackgroundLight = Color(0xFF1D1A23)
private val surfaceLight = Color(0xFFFEF7FF)
private val onSurfaceLight = Color(0xFF1D1A23)
private val surfaceVariantLight = Color(0xFFE8DFF3)
private val onSurfaceVariantLight = Color(0xFF4A4454)
private val outlineLight = Color(0xFF7B7485)
private val outlineVariantLight = Color(0xFFCBC3D6)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF322F38)
private val inverseOnSurfaceLight = Color(0xFFF6EEFB)
private val inversePrimaryLight = Color(0xFFD1BCFF)
private val surfaceDimLight = Color(0xFFDED7E4)
private val surfaceBrightLight = Color(0xFFFEF7FF)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFF8F1FE)
private val surfaceContainerLight = Color(0xFFF3EBF8)
private val surfaceContainerHighLight = Color(0xFFEDE5F2)
private val surfaceContainerHighestLight = Color(0xFFE7E0ED)

private val primaryDark = Color(0xFFD1BCFF)
private val onPrimaryDark = Color(0xFF3D0090)
private val primaryContainerDark = Color(0xFF7645DB)
private val onPrimaryContainerDark = Color(0xFFede1ff)
private val secondaryDark = Color(0xFFD1BCFF)
private val onSecondaryDark = Color(0xFF372561)
private val secondaryContainerDark = Color(0xFF4E3C7A)
private val onSecondaryContainerDark = Color(0xFFC0AAF0)
private val tertiaryDark = Color(0xFFFFB1C8)
private val onTertiaryDark = Color(0xFF650033)
private val tertiaryContainerDark = Color(0xFFC20068)
private val onTertiaryContainerDark = Color(0xFFFFD5E0)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF161616)
private val onBackgroundDark = Color(0xFFE7E0ED)
private val surfaceDark = Color(0xFF161616)
private val onSurfaceDark = Color(0xFFE7E0ED)
private val surfaceVariantDark = Color(0xFF4c4c4c)
private val onSurfaceVariantDark = Color(0xFFCBC3D6)
private val outlineDark = Color(0xFF958EA0)
private val outlineVariantDark = Color(0xFF4A4454)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFE7E0ED)
private val inverseOnSurfaceDark = Color(0xFF322F38)
private val inversePrimaryDark = Color(0xFF6E3CD3)
private val surfaceDimDark = Color(0xFF161616)
private val surfaceBrightDark = Color(0xFF3c3c3c)
private val surfaceContainerLowestDark = Color(0xFF191919)
private val surfaceContainerLowDark = Color(0xFF1f1f1f)
private val surfaceContainerDark = Color(0xFF222222)
private val surfaceContainerHighDark = Color(0xFF2d2d2d)
private val surfaceContainerHighestDark = Color(0xFF383838)

internal val lightScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

internal val darkScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)
